# Generated by Django 4.2.11 on 2024-04-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articles",
            options={},
        ),
        migrations.AlterModelOptions(
            name="menu",
            options={},
        ),
        migrations.AlterField(
            model_name="submenu",
            name="slug",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
