# Generated by Django 4.2.11 on 2024-04-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_articles_options_alter_menu_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submenu",
            name="slug",
            field=models.CharField(max_length=64),
        ),
    ]
