# Generated by Django 4.2.11 on 2024-04-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_alter_articles_slug_alter_submenu_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="author",
            field=models.CharField(default="Кубекина Е.В.", max_length=50),
        ),
    ]
