# Generated by Django 4.2.11 on 2024-04-16 14:25

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_alter_articles_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="image",
            field=models.ImageField(
                blank=True, upload_to=articles.models.Articles.img_path
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="image",
            field=models.ImageField(
                blank=True, upload_to=articles.models.Section.img_path
            ),
        ),
    ]
