# Generated by Django 4.2.11 on 2024-04-19 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_alter_articles_image_alter_section_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="body",
        ),
        migrations.CreateModel(
            name="Paragraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                (
                    "section_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="articles.section",
                    ),
                ),
            ],
        ),
    ]
