# Generated by Django 4.2.11 on 2024-04-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_remove_section_body_paragraph"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paragraph",
            name="body",
        ),
        migrations.AddField(
            model_name="paragraph",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="section",
            name="intro",
            field=models.TextField(blank=True),
        ),
    ]
