# Generated by Django 4.2.11 on 2024-04-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0008_remove_paragraph_body_paragraph_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paragraph",
            name="content",
            field=models.TextField(),
        ),
    ]
