# Generated by Django 4.2.11 on 2024-04-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0010_remove_section_intro_articles_intro"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="base_color",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="menu",
            name="bg_color",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="menu",
            name="image_footer",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="menu",
            name="image_header",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="menu",
            name="image_main",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
