# Generated by Django 4.2.11 on 2024-04-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0011_menu_base_color_menu_bg_color_menu_image_footer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="base_color",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name="menu",
            name="bg_color",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name="menu",
            name="image_footer",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="menu",
            name="image_header",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="menu",
            name="image_main",
            field=models.CharField(max_length=64),
        ),
    ]
