# Generated by Django 4.2.11 on 2024-04-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0012_alter_menu_base_color_alter_menu_bg_color_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articles",
            options={"ordering": ("pk",)},
        ),
        migrations.AlterModelOptions(
            name="menu",
            options={"ordering": ("pk",)},
        ),
        migrations.AlterModelOptions(
            name="paragraph",
            options={"ordering": ("pk",)},
        ),
        migrations.AlterModelOptions(
            name="section",
            options={"ordering": ("pk",)},
        ),
        migrations.AlterModelOptions(
            name="submenu",
            options={"ordering": ("pk",)},
        ),
        migrations.AlterField(
            model_name="articles",
            name="author",
            field=models.CharField(default="Елена Кубекина", max_length=50),
        ),
    ]
