# Generated by Django 4.2.11 on 2024-04-22 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0013_alter_articles_options_alter_menu_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="bottom_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="section_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="articles.section",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="top_text",
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name="Paragraph",
        ),
    ]
