# Generated by Django 4.2.11 on 2024-04-23 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0017_alter_section_articles_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="section_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="myself",
                to="articles.section",
            ),
        ),
    ]
