# Generated by Django 4.2.11 on 2024-04-25 14:17

import articles.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0018_alter_section_section_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articles",
            options={
                "ordering": ("pk",),
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.AlterModelOptions(
            name="menu",
            options={
                "ordering": ("pk",),
                "verbose_name": "Пункт меню",
                "verbose_name_plural": "Пункты меню",
            },
        ),
        migrations.AlterModelOptions(
            name="section",
            options={
                "ordering": ("pk",),
                "verbose_name": "Раздел",
                "verbose_name_plural": "Разделы",
            },
        ),
        migrations.AlterModelOptions(
            name="submenu",
            options={
                "ordering": ("pk",),
                "verbose_name": "Пункт подменю",
                "verbose_name_plural": "Пункты подменю",
            },
        ),
        migrations.AlterField(
            model_name="articles",
            name="author",
            field=models.CharField(
                default="Елена Кубекина", max_length=50, verbose_name="Автор"
            ),
        ),
        migrations.AlterField(
            model_name="articles",
            name="create_date",
            field=models.DateField(auto_now=True, verbose_name="Создана"),
        ),
        migrations.AlterField(
            model_name="articles",
            name="description",
            field=models.TextField(verbose_name="Анонс"),
        ),
        migrations.AlterField(
            model_name="articles",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=articles.models.Articles.img_path,
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="articles",
            name="intro",
            field=models.TextField(blank=True, verbose_name="Вступление"),
        ),
        migrations.AlterField(
            model_name="articles",
            name="name",
            field=models.CharField(
                max_length=128, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="articles",
            name="publish_date",
            field=models.DateField(auto_now_add=True, verbose_name="Опубликована"),
        ),
        migrations.AlterField(
            model_name="articles",
            name="slug",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Слаг"
            ),
        ),
        migrations.AlterField(
            model_name="articles",
            name="submenu_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="articles.submenu",
                verbose_name="Раздел подменю",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="articles_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="articles.articles",
                verbose_name="Статья",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="header",
            field=models.CharField(
                max_length=128, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=articles.models.Section.img_path,
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="section_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="myself",
                to="articles.section",
                verbose_name="Раздел",
            ),
        ),
    ]
